### PR TITLE
Add best papers and runners up

### PR DESCRIPTION
**Pull request by marijnkoolen**
@Mina, when you have time (after the conference closing session), can you add the two announcements, one for the best _long_ paper, one for the best _short_ paper. Thanks!

### CODE REVIEW

**Comment by marijnkoolen** [comment]
Sorry, forgot to add the awards images. I'll push them in a bit, as I'm sitting in a session and don't want people to look over my shoulder and see the awards while I turn them from PDF into a png or so.

**Comment by marijnkoolen** [comment]
Okay, the images are in there. Let me know if you need anything else.

**Comment by MinaAlmasi** [comment]
Hi! I have turned the .md into a general md for both long and short papers but will make headings for each so you can clearly see the distinguishment between long and short paper awards. Any chance you can read the intro paragraph and tell me if it is appropriate? :

# CHR2024 BEST PAPER AWARDS
CHR2024 showcased outstanding work, highlighting cutting-edge computational approaches to humanities research. A heartfelt thank you to everyone who participated, whether by presenting your work or contributing to meaningful discussions at the conference.

We are delighted to reveal the winners of the <span style="font-weight:700;">Best Long Paper</span> and <span style="font-weight:700;">Best Short Paper</span> awards. With so many exceptional submissions, we are pleased to give honourable mentions to the two runners-up in each category.

## Best Long Paper
....
## Best Short Paper
...

**Comment by marijnkoolen** [comment]
This looks perfect. Many thanks!

**Comment by MinaAlmasi** [comment]
Awesome - I'll add the content and merge soon!

**Comment by MinaAlmasi** [comment]
Added the best papers + added an announcement to the announcement page

**Pull request merged**
